service: serverless-budget-notifications

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action: 'budgets:ViewBudget'
      Resource: '*'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  slack:
    handler: bin/main
    memorySize: 128
    environment:
      INCOMING_WEBHOOK_URL: ${env:SLACK_INCOMING_WEBHOOK_URL}
      BUDGET_NAME: ${env:AWS_BUDGET_NAME}
    events:
      - schedule: cron(30 9 * * ? *)
